name: Create Release

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Release description'
        required: false
        default: 'New release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date and time
        id: date
        run: |
          echo "DATE=$(date +'%Y.%m.%d-%H.%M.%S')" >> $GITHUB_OUTPUT
          echo "MANIFEST_VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Update version in manifest.json
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.date.outputs.MANIFEST_VERSION }}"/' source/manifest.json
          cat source/manifest.json

      - name: Create zip file
        run: |
          cd source
          zip -r ../xdebug-helper-for-chrome-${{ steps.date.outputs.DATE }}.zip .
          cd ..

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.date.outputs.DATE }}
          name: Release ${{ steps.date.outputs.DATE }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
          files: |
            ./xdebug-helper-for-chrome-${{ steps.date.outputs.DATE }}.zip
