name: Create Release

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'Release description'
        required: false
        default: 'New release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from manifest.json
        id: version
        run: |
          VERSION=$(node -e "const fs = require('fs'); const manifest = JSON.parse(fs.readFileSync('source/manifest.json', 'utf8')); console.log(manifest.version);")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"

      - name: Create zip file
        run: |
          cd source
          zip -r ../xdebug-helper-for-chrome-v${{ steps.version.outputs.VERSION }}.zip .
          cd ..

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
          files: |
            ./xdebug-helper-for-chrome-v${{ steps.version.outputs.VERSION }}.zip
